---
title: "Modelling of the count of reported cases of Malaria in Loreto over time"
output: html_notebook
---

```{r}
################
# Data loading #
################

data_path <- file.path('_data/') # Data directory path
file_name <- 'dt_final.csv' # csv. file name 
file_path <- file.path(data_path, file_name) # Full csv. file path

library(tidyverse)

# Column names
col_names <- c(
  'district',
  'year',
  'month',
  'falciparum',
  'vivax',
  'aet',
  'prcp',
  'q',
  'soilm',
  'tmax',
  'tmin',
  'water_deficit',
  'loss',
  'loss_km2',
  'cum_loss_km2',
  'diag',
  'enviro',
  'nets',
  'workers',
  'pamafro',
  'pop2015',
  'province',
  'region',
  'id_district'
)

# Column types
col_types <- readr::cols(
  district = col_character(),
  year = col_integer(),
  month = col_integer(),
  falciparum = col_integer(),
  vivax = col_integer(),
  aet = col_double(),
  prcp = col_double(),
  q = col_double(),
  soilm = col_double(),
  tmax = col_double(),
  tmin = col_double(),
  water_deficit = col_double(),
  loss = col_double(),
  loss_km2 = col_double(),
  cum_loss_km2 = col_double(),
  diag = col_integer(),
  enviro = col_integer(),
  nets = col_integer(),
  workers = col_integer(),
  pamafro = col_character(),
  pop2015 = col_integer(),
  province = col_character(),
  region = col_character(),
  id_district = col_character()
)

# Read raw csv. file into a data frame
raw_dataset <- 
  readr::read_csv(
    file = file_path,
    col_names = col_names,
    col_types = col_types,
    skip = 1,
    locale = readr::locale(encoding = "utf-8")
  )

# Create columns
# - report_date: 
# Date of cases report in date-time format
# - control: 
# Flag column indicating if the PAMAFRO intervention was taken place
# in that date
raw_dataset %>% 
  dplyr::mutate(
    reporting_date = 
      lubridate::make_date(
        year = year,
        month = month,
        day = 1L # Take 01 as the day
      ) 
  ) %>% 
  dplyr::mutate(
    intervention = 
      ifelse(
        test = reporting_date < '2005-09-01',
        yes = 1,
        no = ifelse(
          test = reporting_date < '2010-08-01',
          yes = 2,
          no = 3
        )
      ),
    numeric_time = as.numeric(
      factor(
        x = reporting_date, 
        labels = c(as.character(seq(1, 216)))
      )
    )
  ) %>% 
  dplyr::arrange(reporting_date) -> 
  dataset # Final data frame
```

Exploratory data analysis

```{r}
summary(dataset)
```

```{r}
table(dataset$diag)
table(dataset$enviro)
table(dataset$nets)
table(dataset$workers)
table(dataset$pamafro)
```

```{r}
theme_set(theme_linedraw() + 
            theme(
              panel.border = element_blank(),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              axis.line = element_line(colour = "black")
            )
)

library(GGally)

dataset %>%
  dplyr::filter(
    falciparum > 0,
    vivax > 0
  ) %>% 
  dplyr::select(
    falciparum,
    vivax,
    aet,
    prcp,
    q,
    soilm,
    tmax,
    tmin
  ) %>% 
  GGally::ggpairs(
    progress = FALSE
  )
```

```{r}
dataset %>%
  dplyr::filter(
    falciparum > 0,
    vivax > 0
  ) %>%
  dplyr::select(
    falciparum,
    vivax,
    aet,
    prcp,
    q,
    soilm,
    tmax,
    tmin
  ) %>% cor()
```

Base model

```{r}
library(MASS)
library(leaps)

vivax_glm_subsets <- regsubsets(
  x = 
    vivax ~ 
    aet + 
    prcp + 
    q +
    soilm + 
    tmax +
    tmin
  ,
  data = dataset,
  method = "exhaustive"
)

summary(vivax_glm_subsets)
```

```{r}
plot(vivax_glm_subsets, scale = "bic")
```
```{r}
null_model <- 
  glm.nb(
    formula = vivax ~ 1,
    data = dataset
  )

stepAIC(
  object = null_model,
  scope = list(
    upper = vivax ~ soilm + aet + q + tmin + prcp + tmax,
    lower = vivax ~ 1
  ),
  direction = "both",
  trace = TRUE
)
```

```{r}
glm_cross_validation <- function(data, formula, k, seed)
{
  rows <- nrow(data)
  set.seed(seed)
  data <- data[sample(rows),]
  folds <- cut(
    x = seq(1, rows), 
    breaks = k,
    labels = FALSE
  )
  
  cv_rmse <- c()
  cv_mae <- c()
  cv_cor <- c()
  
  for(i in 1:k)
  {
    id_test <- which(
      x = folds == i,
      arr.ind = TRUE
    )
    test <- data[id_test,]
    train <- data[-id_test,]
    
    model <- glm.nb(
      formula = formula,
      data = train
    )
    
    prediction <- predict.glm(
      object = model,
      type = "response",
      newdata = test
    )
    
    actual = as.matrix(test[model$terms[[2]]])
    
    cv_rmse[i] <- sqrt(mean((prediction - actual)^2))
    cv_mae[i] <- mean(abs(prediction - actual))
    cv_cor[i] <- cor(prediction, actual)
  }
  
  rmse <- mean(cv_rmse)
  mae <- mean(cv_mae)
  corr <- mean(cv_cor)
  
  results <- list(
    "rmse" = rmse,
    "mae" = mae,
    "cor" = corr
  )
  
  return(results)
}

glm_model_criteria <- function(formulas, data, k, seed)
{
  library(MASS)
  library(tibble)
  
  models <- list()
  aic <- c()
  bic <- c()
  rmse <- c()
  mae <- c()
  corr <- c()
  
  for(i in 1:length(formulas))
  {
    models[[i]] <- MASS::glm.nb(
      formula = formulas[[i]],
      data = data
    )
    
    aic[i] <- stats::AIC(models[[i]])
    bic[i] <- stats::BIC(models[[i]])
    
    cv_results <- glm_cross_validation(
      data = data,
      formula = formulas[[i]],
      k = 10,
      seed = seed
    )
    
    rmse[i] <- cv_results$rmse
    mae[i] <- cv_results$mae
    corr[i] <- cv_results$cor
    
  }
  
  criteria <- tibble::tibble(
    id = 1:length(formulas),
    model = names(formulas),
    aic = aic,
    bic = bic,
    rmse = rmse,
    mae = mae,
    corr = corr
  )
  
  return(criteria)
}
```

```{r}
vivax_glm_models <- list(
  "m0" = 
    formula(
      vivax ~ 1
    )
  ,
  "m1" = 
    formula(
      vivax ~ soilm
    )
  ,
  "m2" = 
    formula(
      vivax ~ soilm + tmax
    )
  ,
  "m3" = 
    formula(
      vivax ~ soilm + tmax + tmin
    )
  ,
  "m4" = 
    formula(
      vivax ~ soilm + tmax + tmin 
    )
  ,
  "m5" = 
    formula(
      vivax ~ soilm + loss_km2 + aet + water_deficit + q
    )
  ,
  "m6" = 
    formula(
      vivax ~ soilm + loss_km2 + aet + water_deficit + q + tmin
    )
  ,
  "m7" = 
    formula(
      vivax ~ soilm + loss_km2 + aet + water_deficit + q + tmin + prcp
    )
  ,
  "m8" = 
    formula(
      vivax ~ soilm + loss_km2 + aet + water_deficit + q + tmin + prcp + tmax
    )
  ,
  "m6_step" = 
    formula(
      vivax ~ soilm + loss_km2 + aet + water_deficit + tmin + tmax
    )
)

vivax_glm_criteria <- glm_model_criteria(
  formula = vivax_glm_models,
  data = dataset,
  k = 10,
  seed = 123
)

vivax_glm_criteria
```
```{r}
vivax_glm_criteria %>% 
  pivot_longer(
    cols = c(aic, bic),
    names_to = "criteria"
  ) %>% 
  ggplot(
    aes(x = id, y = value, colour = criteria)
  ) +
  geom_line() +
  scale_x_continuous(
    breaks = 1:length(vivax_glm_criteria$model),
    labels = vivax_glm_criteria$model
  )
```
GLM model

```{r}
vivax_glm_full <- MASS::glm.nb(
  formula = vivax ~ soilm + aet + prcp + tmax + tmin, 
  data = dataset
)

summary(vivax_glm_full)
```

```{r}
dataset %>% 
  dplyr::mutate(
    aet_mc = aet - mean(aet),
    prcp_mc = prcp - mean(prcp),
    q_mc = q - mean(q),
    soilm_mc = soilm - mean(soilm),
    tmax_mc = tmax - mean(tmax),
    tmin_mc = tmin - mean(tmin)
  ) -> dataset
```


```{r}
library(lme4)

vivax_glmer_re <- glmer.nb(
  formula = vivax ~ soilm_mc + (1|id_district),
  data = dataset,
  control = glmerControl(
    optimizer = "bobyqa"
  )
)

summary(vivax_glmer_re)
```


```{r}
vivax_glm_model <- glm.nb(
  formula = vivax ~ soilm + loss_km2 + aet + water_deficit,
  data = dataset
)

summary(vivax_glm_model)
AIC(vivax_glm_model)
```

```{r}
logLik(vivax_glm_model)
```

GAM

```{r}
library(mgcv)

dataset$pamafro = factor(dataset$pamafro)
dataset$control = factor(dataset$control)
```

```{r}
library(mgcv)
vivax_gam_v1 <- mgcv::gam(
  formula = 
    formula(vivax ~ 
    s(t, by = soilm) + 
    s(t, by = loss_km2) + 
    s(t, by = aet) + 
    s(t, by = water_deficit))
  ,
  familiy = nb(link = "log"),
  data = dataset,
  method = "REML"
)

summary(vivax_gam_v1)
stats::AIC(vivax_gam_v1)
logLik.gam(vivax_gam_v1)
```

```{r}
gam_cross_validation <- function(data, formula, k, seed)
{
  library(mgcv, warn.conflicts = FALSE)
  
  rows <- nrow(data)
  set.seed(seed)
  data <- data[sample(rows),]
  folds <- cut(
    x = seq(1, rows), 
    breaks = k,
    labels = FALSE
  )
  
  cv_rmse <- c()
  cv_mae <- c()
  cv_cor <- c()
  
  for(i in 1:k)
  {
    id_test <- which(
      x = folds == i,
      arr.ind = TRUE
    )
    test <- data[id_test,]
    train <- data[-id_test,]
    
    model <- mgcv::gam(
      formula = formula,
      family = mgcv::nb(),
      data = train
    )
    
    prediction <- predict.gam(
      object = model,
      type = "response",
      newdata = test
    )
    
    prediction <- as.matrix(prediction, ncol = 1)
    
    actual = as.matrix(test[model$terms[[2]]], ncol = 1)
    
    cv_rmse[i] <- sqrt(mean((prediction - actual)^2))
    cv_mae[i] <- mean(abs(prediction - actual))
    cv_cor[i] <- cor(prediction, actual)
  }
  
  rmse <- mean(cv_rmse)
  mae <- mean(cv_mae)
  corr <- mean(cv_cor)
  
  results <- list(
    "rmse" = rmse,
    "mae" = mae,
    "cor" = corr
  )
  
  return(results)
}

gam_model_criteria <- function(formulas, data, k, seed)
{
  library(mgcv, warn.conflicts = FALSE)
  library(tibble)
  
  models <- list()
  aic <- c()
  rmse <- c()
  mae <- c()
  corr <- c()
  
  for(i in 1:length(formulas))
  {
    models[[i]] <- mgcv::gam(
      formula = formulas[[i]],
      family = nb(),
      data = data
    )
    
    aic[i] <- stats::AIC(models[[i]])
    
    cv_results <- gam_cross_validation(
      data = data,
      formula = formulas[[i]],
      k = k,
      seed = seed
    )
    
    rmse[i] <- cv_results$rmse
    mae[i] <- cv_results$mae
    corr[i] <- cv_results$cor
    
  }
  
  criteria <- tibble::tibble(
    id = 1:length(formulas),
    model = names(formulas),
    aic = aic,
    rmse = rmse,
    mae = mae,
    corr = corr
  )
  
  results <- list(
    "criteria" = criteria,
    "models" = models
  )
  return(results)
}
```


```{r}
vivax_gam_models <- 
  list(
    "glm" = formula(
       vivax ~ 
         s(t, by = soilm) + 
         s(t, by = loss_km2) + 
         s(t, by = aet) + 
         s(t, by = water_deficit)
    ),
    "m1" = formula(
       vivax ~ 
         s(id_district) +
         s(t) +
         s(t, by = soilm) + 
         s(t, by = loss_km2) + 
         s(t, by = aet) + 
         s(t, by = water_deficit)
    )
  )

vivax_gam_criteria <- gam_model_criteria(
  formulas = vivax_gam_models,
  data = dataset,
  k = 5,
  seed = 123
)

vivax_gam_criteria
```

```{r}
vivax_model_test <- gam(
  formula = vivax_gam_models[[1]],
  familiy = nb(),
  data = dataset
)

summary(vivax_model_test)
stats::AIC(vivax_model_test)
```

```{r}
vivax_model_v3 <- gam(
  formula = vivax ~ s(month) + s(t) + s(t, by = soilm),
  familiy = nb(),
  data = dataset
)

summary(vivax_model_v3)
AIC(vivax_model_v3)
```

```{r}
vivax_model_v4 <- gam(
  formula = vivax ~ s(id_district, bs="re") + s(month) + s(t) + s(month, id_district, by = soilm, bs = 'tp'),
  familiy = nb(),
  data = dataset
)

summary(vivax_model_v4)
AIC(vivax_model_v4)
```

Adding s(month, id_district) improves a lot the model.

```{r}
dataset$id_province <- as.numeric(factor(dataset$province))

vivax_model_v5 <- gam(
  formula = vivax ~ 
    s(id_district) + 
    s(month) + 
    s(month, id_district, by = soilm, bs = 'tp') +
    s(month, id_district) + # isotropic
    s(t, id_district) +
    s(year, id_district)
  ,
  familiy = nb(),
  data = dataset
)

summary(vivax_model_v5)
AIC(vivax_model_v5)
```

```{r}
vivax_model_v6 <- gam(
  formula = vivax ~ 
    s(id_district) + 
    s(month) + 
    s(month, id_district, by = soilm, bs = 'tp') +
    s(month, id_district) + # isotropic
    s(t, id_district) +
    s(year, id_district) +
    s(year, id_district) +
    te(year, month, id_district) +
    s(soilm, tmax)
  ,
  familiy = nb(),
  data = dataset
)

summary(vivax_model_v6)
AIC(vivax_model_v6)
```

```{r}
vivax_model_v7 <- gam(
  formula = vivax ~ 
    s(id_district) + 
    s(year) + 
    #te(month, id_district, by = soilm) +
    s(year, month, id_district, by = soilm) +
    # s(year, month, id_district, by = tmax) +
    s(month, id_district) + # isotropic
    s(year, id_district) +
    te(year, month, id_district) +
    s(soilm, tmax)
  ,
  familiy = nb(),
  data = dataset
)

summary(vivax_model_v7)
AIC(vivax_model_v7)
```

```{r}
vivax_model_v8 <- gam(
  formula = vivax ~ 
    s(id_district) + 
    s(year) + 
    #te(month, id_district, by = soilm) +
    s(year, month, id_district, by = soilm) +
    # s(year, month, id_district, by = tmax) +
    s(month, id_district) + # isotropic
    s(year, id_district) +
    te(year, month, id_district) +
    s(soilm, tmax) +
    pamafro
  ,
  familiy = nb(),
  data = dataset
)

summary(vivax_model_v8)
AIC(vivax_model_v8)
```

```{r}
vivax_model_v9 <- gam(
  formula = vivax ~ 
    s(id_district) + 
    s(year) + 
    #te(month, id_district, by = soilm) +
    s(year, month, id_district, by = soilm) +
    # s(year, month, id_district, by = tmax) +
    s(month, id_district) + # isotropic
    s(year, id_district) +
    te(year, month, id_district) +
    s(soilm, tmax, by = pamafro) +
    pamafro
  ,
  familiy = nb(),
  data = dataset,
  drop.intercept = TRUE
)

summary(vivax_model_v9)
AIC(vivax_model_v9)
```

# Probar con `control`


















